//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidiSheetMusic.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidiSheetMusic.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Signature.
        /// </summary>
        internal static string changeKeyMenu {
            get {
                return ResourceManager.GetString("changeKeyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Colors....
        /// </summary>
        internal static string chooseColorMenu {
            get {
                return ResourceManager.GetString("chooseColorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Note Colors.
        /// </summary>
        internal static string chooseColorsTitle {
            get {
                return ResourceManager.GetString("chooseColorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Instruments....
        /// </summary>
        internal static string chooseInstrumentsMenu {
            get {
                return ResourceManager.GetString("chooseInstrumentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Instruments For Each Track.
        /// </summary>
        internal static string chooseInstrumentsTitle {
            get {
                return ResourceManager.GetString("chooseInstrumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string closeMenu {
            get {
                return ResourceManager.GetString("closeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string colorMenu {
            get {
                return ResourceManager.GetString("colorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine Notes Within Interval.
        /// </summary>
        internal static string combineNotesMenu {
            get {
                return ResourceManager.GetString("combineNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine All Tracks Into Two Staffs.
        /// </summary>
        internal static string combineStaffMenu {
            get {
                return ResourceManager.GetString("combineStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All Tracks.
        /// </summary>
        internal static string deselectAllTracksMenu {
            get {
                return ResourceManager.GetString("deselectAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Measure.
        /// </summary>
        internal static string endMeasure {
            get {
                return ResourceManager.GetString("endMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitMenu {
            get {
                return ResourceManager.GetString("exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Forward.
        /// </summary>
        internal static string fastForward {
            get {
                return ResourceManager.GetString("fastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileMenu {
            get {
                return ResourceManager.GetString("fileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Contents....
        /// </summary>
        internal static string helpContentsMenu {
            get {
                return ResourceManager.GetString("helpContentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string helpMenu {
            get {
                return ResourceManager.GetString("helpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Notes.
        /// </summary>
        internal static string largeNotesMenu {
            get {
                return ResourceManager.GetString("largeNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Length.
        /// </summary>
        internal static string measureMenu {
            get {
                return ResourceManager.GetString("measureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string milliseconds {
            get {
                return ResourceManager.GetString("milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute All Tracks.
        /// </summary>
        internal static string muteAllTracksMenu {
            get {
                return ResourceManager.GetString("muteAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newMenu {
            get {
                return ResourceManager.GetString("newMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notesMenu {
            get {
                return ResourceManager.GetString("notesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show One Staff Per Track.
        /// </summary>
        internal static string oneStaffMenu {
            get {
                return ResourceManager.GetString("oneStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string openMenu {
            get {
                return ResourceManager.GetString("openMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sample Song....
        /// </summary>
        internal static string openSampleSongMenu {
            get {
                return ResourceManager.GetString("openSampleSongMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Measures in a Loop....
        /// </summary>
        internal static string playMeasuresMenu {
            get {
                return ResourceManager.GetString("playMeasuresMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Selected Measures in a Loop.
        /// </summary>
        internal static string playMeasuresTitle {
            get {
                return ResourceManager.GetString("playMeasuresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview....
        /// </summary>
        internal static string previewMenu {
            get {
                return ResourceManager.GetString("previewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        internal static string printMenu {
            get {
                return ResourceManager.GetString("printMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pulses.
        /// </summary>
        internal static string pulses {
            get {
                return ResourceManager.GetString("pulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind.
        /// </summary>
        internal static string rewind {
            get {
                return ResourceManager.GetString("rewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Sample MIDI Song.
        /// </summary>
        internal static string sampleSongTitle {
            get {
                return ResourceManager.GetString("sampleSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Images....
        /// </summary>
        internal static string saveImagesMenu {
            get {
                return ResourceManager.GetString("saveImagesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As PDF....
        /// </summary>
        internal static string savePDFMenu {
            get {
                return ResourceManager.GetString("savePDFMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Horizontally.
        /// </summary>
        internal static string scrollHorizMenu {
            get {
                return ResourceManager.GetString("scrollHorizMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Vertically.
        /// </summary>
        internal static string scrollVertMenu {
            get {
                return ResourceManager.GetString("scrollVertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Tracks.
        /// </summary>
        internal static string selectAllTracksMenu {
            get {
                return ResourceManager.GetString("selectAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All To Piano.
        /// </summary>
        internal static string setAllPiano {
            get {
                return ResourceManager.GetString("setAllPiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Notes.
        /// </summary>
        internal static string shiftNotesMenu {
            get {
                return ResourceManager.GetString("shiftNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 1/2 note.
        /// </summary>
        internal static string shiftRight12 {
            get {
                return ResourceManager.GetString("shiftRight12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 1/4 note.
        /// </summary>
        internal static string shiftRight14 {
            get {
                return ResourceManager.GetString("shiftRight14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 1/8 note.
        /// </summary>
        internal static string shiftRight18 {
            get {
                return ResourceManager.GetString("shiftRight18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 3/4 note.
        /// </summary>
        internal static string shiftRight34 {
            get {
                return ResourceManager.GetString("shiftRight34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 3/8 note.
        /// </summary>
        internal static string shiftRight38 {
            get {
                return ResourceManager.GetString("shiftRight38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 5/8 note.
        /// </summary>
        internal static string shiftRight58 {
            get {
                return ResourceManager.GetString("shiftRight58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right 7/8 note.
        /// </summary>
        internal static string shiftRight78 {
            get {
                return ResourceManager.GetString("shiftRight78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string showDefault {
            get {
                return ResourceManager.GetString("showDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Do-Re-Mi.
        /// </summary>
        internal static string showFixedDoReMi {
            get {
                return ResourceManager.GetString("showFixedDoReMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Numbers.
        /// </summary>
        internal static string showFixedNumbers {
            get {
                return ResourceManager.GetString("showFixedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        internal static string showLetters {
            get {
                return ResourceManager.GetString("showLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Note Letters.
        /// </summary>
        internal static string showLettersMenu {
            get {
                return ResourceManager.GetString("showLettersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lyrics.
        /// </summary>
        internal static string showLyricsMenu {
            get {
                return ResourceManager.GetString("showLyricsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Measure Numbers.
        /// </summary>
        internal static string showMeasuresMenu {
            get {
                return ResourceManager.GetString("showMeasuresMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movable Do-Re-Mi.
        /// </summary>
        internal static string showMovableDoReMi {
            get {
                return ResourceManager.GetString("showMovableDoReMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movable Numbers.
        /// </summary>
        internal static string showMovableNumbers {
            get {
                return ResourceManager.GetString("showMovableNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Notes.
        /// </summary>
        internal static string smallNotesMenu {
            get {
                return ResourceManager.GetString("smallNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Track Into Two Staffs.
        /// </summary>
        internal static string splitStaffMenu {
            get {
                return ResourceManager.GetString("splitStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Measure.
        /// </summary>
        internal static string startMeasure {
            get {
                return ResourceManager.GetString("startMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature.
        /// </summary>
        internal static string timeSigMenu {
            get {
                return ResourceManager.GetString("timeSigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tracks to Display.
        /// </summary>
        internal static string trackDisplayMenu {
            get {
                return ResourceManager.GetString("trackDisplayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string trackMenu {
            get {
                return ResourceManager.GetString("trackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tracks to Mute.
        /// </summary>
        internal static string trackMuteMenu {
            get {
                return ResourceManager.GetString("trackMuteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transpose.
        /// </summary>
        internal static string transposeMenu {
            get {
                return ResourceManager.GetString("transposeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute All Tracks.
        /// </summary>
        internal static string unmuteAllTracksMenu {
            get {
                return ResourceManager.GetString("unmuteAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Color.
        /// </summary>
        internal static string useColorMenu {
            get {
                return ResourceManager.GetString("useColorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string viewMenu {
            get {
                return ResourceManager.GetString("viewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string volume {
            get {
                return ResourceManager.GetString("volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string writeMenu {
            get {
                return ResourceManager.GetString("writeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to 100%.
        /// </summary>
        internal static string zoom100Menu {
            get {
                return ResourceManager.GetString("zoom100Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to 150%.
        /// </summary>
        internal static string zoom150Menu {
            get {
                return ResourceManager.GetString("zoom150Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string zoomInMenu {
            get {
                return ResourceManager.GetString("zoomInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string zoomOutMenu {
            get {
                return ResourceManager.GetString("zoomOutMenu", resourceCulture);
            }
        }
    }
}
